version: "3.8"

services:
  db-postgres-wallet:
    container_name: wallet
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: wallet-challenges
    ports:
      - "5432:5432"
  